language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
  - composer install --prefer-source
  - npm install
  - npm install -g jest-cli

script:
    - phpunit
    - jest

notifications:
    email: false