security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|stylesheets|images|scripts)/
            security: false

        default:
            anonymous: ~
