<?php

namespace Airlines\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    /**
     * Fetches Tasks by Member and date(s)
     *
     * @param Member $member
     * @param array  $dates  Array of YYYY-MM-DD date strings
     */
    public function findByMemberAndDates(Member $member, array $dates)
    {
        return $this->createQueryBuilder('t')
                    ->where('t.date IN(:dates)')
                    ->andWhere('t.member = :member')
                    ->setParameter('dates', $dates)
                    ->setParameter('member', $member->getId())
                    ->orderBy('t.id', 'ASC')
                    ->getQuery()
                    ->getResult();
    }
}
