<?php

namespace Airlines\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    /**
     * Fetches tasks by member and date
     *
     * @param Member $member Member instance
     * @param string $date   SQL-formatted date
     */
    public function findByMemberAndDate(Member $member, $date)
    {
        return $this->findBy(
            [
                'member' => $member->getId(),
                'date' => new \DateTime($date)
            ]
        );
    }
}
