<?php

namespace Airlines\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeekRepository extends EntityRepository
{
}
